services:
  web:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn main:app --bind :80
    networks:
      - nginx_network
    
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/fsdcbackend.ddns.net/fullchain.pem:/etc/letsencrypt/live/fsdcbackend.ddns.net/fullchain.pem/
      - /etc/letsencrypt/live/fsdcbackend.ddns.net/privkey.pem:/etc/letsencrypt/live/fsdcbackend.ddns.net/privkey.pem
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
