services:
  web:
    build: ./fastapi.Dockerfile
    command: fastapi dev main.py
    expose:
      - 8000
  nginx:
    build: ./nginx/nginx.Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web

